CLASS y234_abaptest DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS y234_abaptest IMPLEMENTATION.
METHOD if_oo_adt_classrun~main.
out->write( 'HELLO WORLD' ).
ENDMETHOD.
ENDCLASS.
